version: '3'
services: 
    redis-server:
        image: 'redis'
        restart: "on-failure"
    node-app:
        build: .
        ports: 
            - "8080:8080"
        restart: "always"        